version: '3.7'

volumes:
  mongodb:
  minio:

services:
  traefik:
    image: traefik:v2.2
    command: 
      - '--api.insecure=true' 
      - '--providers.docker'
      - '--providers.file.directory=/etc/traefik/dynamic_conf'
      - '--entrypoints.http.address=:80'
      - '--entrypoints.https.address=:443'
      - '--providers.docker.exposedByDefault=false'
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080'
    volumes:
      - './traefik/dynamic_conf:/etc/traefik/dynamic_conf'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/etc/certs:/etc/certs:ro'
    restart: always

  mongodb:
    image: 'mongo:latest'
    volumes:
      - 'mongodb:/data/db'
    command: --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: a_Secure_And_Secret_Good_Password!
    restart: always

  minio:
    image: 'minio/minio:latest'
    expose:
      - '9000'
    volumes:
      - 'minio:/data'
    environment:
      MINIO_ACCESS_KEY:    'minio_access_key'
      MINIO_SECRET_KEY:    'minio_secret_key'
      MINIO_REGION_NAME:   'us-east-1'
    command: server /data
    restart: always

  redis:
    image: 'redis:latest'
    expose:
      - '6379'
    restart: always

  myrunes-be:
    image: 'myrunes/backend:latest'
    expose:
      - '9000'
    volumes:
      - './myrunes:/etc/myrunes'
    restart: always
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.myrunes-be.entrypoints=https'
      - 'traefik.http.routers.myrunes-be.tls=true'
      - 'traefik.http.routers.myrunes-be.rule=PathPrefix(`/api`)'
      - 'traefik.http.routers.myrunes-be.middlewares=myrunes-be-stripprefix'
      - 'traefik.http.middlewares.myrunes-be-stripprefix.stripprefix.prefixes=/api'

  myrunes-fe:
    image: 'myrunes/frontend:latest'
    expose:
      - '8080'
    restart: on-failure
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.myrunes-fe.entrypoints=https'
      - 'traefik.http.routers.myrunes-fe.tls=true'
      - 'traefik.http.routers.myrunes-fe.rule=PathPrefix(`/`)'
      - 'traefik.http.services.myrunes-fe.loadbalancer.server.port=8080'
