mongodb:
  auth_db:  admin
  data_db:  lol-runes
  host:     mongodb
  username: admin
            # PLEASE CHANGE THIS
  password: a_Secure_And_Secret_Good_Password!
  port:     27017

redis:
  enabled: false
  addr:    'redis:6379'
  db: 0
  password: ""

webserver:
  addr:          'myrunes-backend:8080'
  publicaddress: 'http://localhost'
  enablecors:    false
  tls:
    enabled: false

mailserver:
  host:     'smtp.mailservice.com'
  port:     465
  username: 'webmaster@mailservice.com'
  password: 'your_mail_server_password'
