mongodb:
  auth_db:  admin
  data_db:  lol-runes
  host:     mongodb
  username: admin
  password: a_Secure_And_Secret_Good_Password!
  port:     27017

redis:
  enabled: false
  addr:    'redis:6379'
  db:      0

webserver:
  addr:          ':8080'
  publicaddress: 'http://localhost'
  enablecors:    false
  tls:
    enabled: false

mailserver:
  host:     'smtp.mailservice.com'
  port:     465
  username: 'webmaster@mailservice.com'
  password: 'your_mail_server_password'

storage:
  type: minio
  minio:
    endpoint:      'minio'
    access_key:    'minio_access_key'
    access_secret: 'minio_access_secret'
    location:      'us-east-1'
    secure:        true
